= Google C++ Utilities

C++ STL is still not enough to cover daily development. Google has some great utility codes in their projects located under the `base` or `utils` folder.

This project don't port well-known libraries features:

. link:https://github.com/abseil/abseil-cpp/[Abseil] for many common libraries such as higher C++ standard backports, string utilities, time & synchronization, etc.
. link:https://github.com/google/glog[GLOG] for logging
. link:https://github.com/census-instrumentation/opencensus-cpp[OpenCensus] for metrics

== Workflow

We use copybara as the workflow engine to port source codes from different repositories into our repository.

Please modify the `../copy.bara.sky` file for porting new files.

== Google projects

We would prefer to collect codes from Google's well-known open-source projects:

. link:https://source.chromium.org/chromium/chromium/src?originalUrl=https:%2F%2Fcs.chromium.org%2F[Chromium]
. link:https://github.com/google/leveldb/[LevelDB]
. link:https://github.com/tensorflow/tensorflow/[TensorFlow]
. link:https://github.com/google/or-tools/[OR-Tools]
. link:https://github.com/grpc/grpc[gRPC]
. link:https://github.com/protocolbuffers/protobuf[Protocol Buffers]

See link:https://opensource.google/projects/list/featured?language=c%2B%2B[Google Open Source] for more projects.

We prefer codes from other projects than Chromium because it has complex dependencies in usual.

== Adopted utilities

=== MapUtil

Helper methods such as looking up & inserting for `std::map` & `std::unordered_map`.

Found in following projects:

* link:https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/core/lib/gtl/map_util.h[TensorFlow]
* link:https://github.com/protocolbuffers/protobuf/blob/v3.12.3/src/google/protobuf/stubs/map_util.h[Protocol Buffers]
* link:https://github.com/google/or-tools/blob/v7.7/ortools/base/map_util.h[OR-Tools]

We adopted the one from TensorFlow because it's more active.

=== StlUtil (Won't adopt)

Won't adopt it because there are builtin methods since C++11.

TensorFlow removed it since v2.1.0-rc0
