= Google C++ Utilities

C++ STL is still not enough to cover daily development. Google has some great utility codes in their projects located under the `base` or `utils` folder.

This project don't port well-known libraries features:

. Abseil
. GLOG

== Workflow

We use copybara as the workflow engine to port source codes from different repositories into our repository.

Please modify the `../copy.bara.sky` file for porting new files.

== Google projects

We would prefer to collect codes from Google's well-known open-source projects:

. Chromium
. LevelDB
. TensorFlow
. OR-Tools
. gRPC
. Protocol Buffers

See link:https://opensource.google/projects/list/featured?language=c%2B%2B[Google Open Source] for more projects.

== Adopted utilities

=== MapUtil

Helper methods such as looking up & inserting for `std::map` & `std::unordered_map`.

Found in following projects:

* link:https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/core/lib/gtl/map_util.h[TensorFlow]
* link:https://github.com/google/or-tools/blob/v7.7/ortools/base/map_util.h[OR-Tools]

We adopted the one from TensorFlow because it's more active.

=== StlUtil (Won't adopt)

Won't adopt it because there are builtin methods since C++11.

TensorFlow removed it since v2.1.0-rc0
