# Copyright (c) 2022 Zhang Shuai<zhangshuai.ustc@gmail.com>.
# All rights reserved.
#
# This file is part of ONE.
#
# ONE is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# ONE is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# ONE. If not, see <https://www.gnu.org/licenses/>.

jobs:
- job: build
  timeoutInMinutes: 240
  steps:
  - checkout: self
    clean: true
  - task: AzureKeyVault@2.211.1
    displayName: Get ApiKey from Azure KeyVault
    inputs:
      connectedServiceName: 'Isolated'
      keyVaultName: 'shuaizhang-akv'
      secretsFilter: 'BuildBuddyApiKey'
  - bash: tools/setup_clang.sh /usr/lib/llvm-14
    displayName: Setup for Bazel build with clang
  - bash: .azure-pipelines/common/get_source_branch_name.sh
    displayName: Set source branch name for BuildBuddy
  - task: DownloadPipelineArtifact@2.198.0
    displayName: Download distdir
    inputs:
      buildType: 'specific'
      project: 'GitHub ADO'
      definition: 'One-distdir-Official'
  - script: >
      bazel
      --batch_cpu_scheduling
      build
      --noshow_loading_progress
      --show_progress_rate_limit=5
      --verbose_failures
      --config=buildbuddy
      --remote_header=x-buildbuddy-api-key=$(BuildBuddyApiKey)
      --build_metadata=REPO_URL=$(Build.Repository.Uri)
      --build_metadata=BRANCH_NAME=$(BuildBuddy.SourceBranchName)
      --build_metadata=COMMIT_SHA=$(Build.SourceVersion)
      --build_metadata=BUILDBUDDY_LINKS="[Azure Pipelines]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(System.JobId))"
      --build_metadata=ALLOW_ENV=AGENT_MACHINENAME,AGENT_NAME,AGENT_OS,AGENT_OSARCHITECTURE,BUILD_BUILDURI,BUILD_REASON,SYSTEM_JOBDISPLAYNAME,SYSTEM_JOBID,SYSTEM_JOBNAME
      --build_metadata=ROLE=CI
      --distdir=$(Pipeline.Workspace)/distdir
      --config=libc++
      //...
    displayName: Build project

- job: test
  timeoutInMinutes: 240
  steps:
  - checkout: self
    clean: true
  - task: AzureKeyVault@2.211.1
    displayName: Get ApiKey from Azure KeyVault
    inputs:
      connectedServiceName: 'Isolated'
      keyVaultName: 'shuaizhang-akv'
      secretsFilter: 'BuildBuddyApiKey'
  - bash: tools/setup_clang.sh /usr/lib/llvm-14
    displayName: Setup for Bazel build with clang
  - bash: .azure-pipelines/common/get_source_branch_name.sh
    displayName: Set source branch name for BuildBuddy
  - task: DownloadPipelineArtifact@2.198.0
    displayName: Download distdir
    inputs:
      buildType: 'specific'
      project: 'GitHub ADO'
      definition: 'One-distdir-Official'
  - script: >
      bazel
      --batch_cpu_scheduling
      test
      --noshow_loading_progress
      --show_progress_rate_limit=5
      --verbose_failures
      --config=buildbuddy
      --remote_header=x-buildbuddy-api-key=$(BuildBuddyApiKey)
      --build_metadata=REPO_URL=$(Build.Repository.Uri)
      --build_metadata=BRANCH_NAME=$(BuildBuddy.SourceBranchName)
      --build_metadata=COMMIT_SHA=$(Build.SourceVersion)
      --build_metadata=BUILDBUDDY_LINKS="[Azure Pipelines]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(System.JobId))"
      --build_metadata=ALLOW_ENV=AGENT_MACHINENAME,AGENT_NAME,AGENT_OS,AGENT_OSARCHITECTURE,BUILD_BUILDURI,BUILD_REASON,SYSTEM_JOBDISPLAYNAME,SYSTEM_JOBID,SYSTEM_JOBNAME
      --build_metadata=ROLE=CI
      --distdir=$(Pipeline.Workspace)/distdir
      --compilation_mode opt
      --config=clang-asan
      --
      //...
    displayName: Test project
