jobs:
- job: build
  timeoutInMinutes: 240
  steps:
  - checkout: self
    clean: true
  - task: AzureKeyVault@2
    displayName: Get ApiKey from Azure KeyVault
    inputs:
      connectedServiceName: 'Isolated'
      keyVaultName: 'shuaizhang-akv'
      secretsFilter: 'BuildBuddyApiKey'
  - bash: tools/setup_clang.sh /usr/lib/llvm-14
    displayName: Setup for Bazel build with clang
  - script: >
      bazel
      --batch_cpu_scheduling
      build
      --noshow_loading_progress
      --show_progress_rate_limit=5
      --verbose_failures
      --config=buildbuddy
      --remote_header=x-buildbuddy-api-key=$(BuildBuddyApiKey)
      --build_metadata=REPO_URL=$(Build.Repository.Uri)
      --build_metadata=BRANCH_NAME=$(Build.SourceBranchName)
      --build_metadata=COMMIT_SHA=$(Build.SourceVersion)
      --build_metadata=BUILDBUDDY_LINKS="[Azure Pipelines]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=results)"
      --build_metadata=ALLOW_ENV=AGENT_MACHINENAME,AGENT_NAME,AGENT_OS,AGENT_OSARCHITECTURE,BUILD_BUILDURI,BUILD_REASON,SYSTEM_JOBDISPLAYNAME,SYSTEM_JOBID,SYSTEM_JOBNAME
      --build_metadata=ROLE=CI
      --config=libc++
      //...
    displayName: Build project

- job: test
  timeoutInMinutes: 240
  steps:
  - checkout: self
    clean: true
  - task: AzureKeyVault@2
    displayName: Get ApiKey from Azure KeyVault
    inputs:
      connectedServiceName: 'Isolated'
      keyVaultName: 'shuaizhang-akv'
      secretsFilter: 'BuildBuddyApiKey'
  - bash: tools/setup_clang.sh /usr/lib/llvm-14
    displayName: Setup for Bazel build with clang
  - script: >
      bazel
      --batch_cpu_scheduling
      test
      --noshow_loading_progress
      --show_progress_rate_limit=5
      --verbose_failures
      --config=buildbuddy
      --remote_header=x-buildbuddy-api-key=$(BuildBuddyApiKey)
      --build_metadata=REPO_URL=$(Build.Repository.Uri)
      --build_metadata=BRANCH_NAME=$(Build.SourceBranchName)
      --build_metadata=COMMIT_SHA=$(Build.SourceVersion)
      --build_metadata=BUILDBUDDY_LINKS="[Azure Pipelines]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=results)"
      --build_metadata=ALLOW_ENV=AGENT_MACHINENAME,AGENT_NAME,AGENT_OS,AGENT_OSARCHITECTURE,BUILD_BUILDURI,BUILD_REASON,SYSTEM_JOBDISPLAYNAME,SYSTEM_JOBID,SYSTEM_JOBNAME
      --build_metadata=ROLE=CI
      --compilation_mode opt
      --config=clang-asan
      --
      //...
      -//third_party/wangle:SSLContextManagerTest
    displayName: Test project
